// +build ignore

// This program generates sentence_data.go from SentenceBreakProperty.txt
// Run with: go run generate_sentence_data.go

package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

type sbRange struct {
	start    rune
	end      rune
	property string
}

func main() {
	file, err := os.Open("SentenceBreakProperty.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error opening file: %v\n", err)
		fmt.Fprintf(os.Stderr, "Please download SentenceBreakProperty.txt from:\n")
		fmt.Fprintf(os.Stderr, "https://www.unicode.org/Public/17.0.0/ucd/auxiliary/SentenceBreakProperty.txt\n")
		os.Exit(1)
	}
	defer file.Close()

	var ranges []sbRange
	scanner := bufio.NewScanner(file)
	var version string

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Extract version from first line
		if version == "" && strings.HasPrefix(line, "# SentenceBreakProperty-") {
			version = strings.TrimPrefix(line, "# SentenceBreakProperty-")
			version = strings.TrimSuffix(version, ".txt")
		}

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Skip @missing lines
		if strings.HasPrefix(line, "@missing") {
			continue
		}

		// Split on semicolon
		parts := strings.Split(line, ";")
		if len(parts) < 2 {
			continue
		}

		codePoints := strings.TrimSpace(parts[0])
		property := strings.TrimSpace(parts[1])

		// Extract just the property value (before the #)
		if idx := strings.Index(property, "#"); idx != -1 {
			property = strings.TrimSpace(property[:idx])
		}

		// Parse code point or range
		var start, end rune
		if strings.Contains(codePoints, "..") {
			// Range
			rangeParts := strings.Split(codePoints, "..")
			startVal, _ := strconv.ParseInt(rangeParts[0], 16, 32)
			endVal, _ := strconv.ParseInt(rangeParts[1], 16, 32)
			start = rune(startVal)
			end = rune(endVal)
		} else {
			// Single code point
			val, _ := strconv.ParseInt(codePoints, 16, 32)
			start = rune(val)
			end = rune(val)
		}

		ranges = append(ranges, sbRange{start: start, end: end, property: property})
	}

	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "Error reading file: %v\n", err)
		os.Exit(1)
	}

	// Sort ranges by start code point for binary search
	sort.Slice(ranges, func(i, j int) bool {
		return ranges[i].start < ranges[j].start
	})

	// Generate the output file
	out, err := os.Create("sentence_data.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate_sentence_data.go DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: Unicode SentenceBreakProperty-%s.txt\n", version)
	fmt.Fprintf(out, "\npackage uax29\n\n")
	fmt.Fprintf(out, "type sbRange struct {\n")
	fmt.Fprintf(out, "\tstart rune\n")
	fmt.Fprintf(out, "\tend   rune\n")
	fmt.Fprintf(out, "\tclass SentenceBreakClass\n")
	fmt.Fprintf(out, "}\n\n")
	fmt.Fprintf(out, "// sentenceBreakData contains all Unicode Sentence_Break property assignments\n")
	fmt.Fprintf(out, "var sentenceBreakData = []sbRange{\n")

	for _, r := range ranges {
		var class string
		switch r.property {
		case "CR":
			class = "SBCR"
		case "LF":
			class = "SBLF"
		case "Sep":
			class = "SBSep"
		case "Extend":
			class = "SBExtend"
		case "Format":
			class = "SBFormat"
		case "Sp":
			class = "SBSp"
		case "Lower":
			class = "SBLower"
		case "Upper":
			class = "SBUpper"
		case "OLetter":
			class = "SBOLetter"
		case "ATerm":
			class = "SBATerm"
		case "STerm":
			class = "SBSTerm"
		case "Numeric":
			class = "SBNumeric"
		case "SContinue":
			class = "SBSContinue"
		case "Close":
			class = "SBClose"
		default:
			// Skip Other - it's the default
			continue
		}

		if r.start == r.end {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, %s}, // U+%04X\n", r.start, r.end, class, r.start)
		} else {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, %s}, // U+%04X..U+%04X\n", r.start, r.end, class, r.start, r.end)
		}
	}

	fmt.Fprintf(out, "}\n")
	fmt.Println("Generated sentence_data.go successfully")
	fmt.Printf("Total ranges: %d\n", len(ranges))
}
