//go:build ignore
// +build ignore

// This program generates word_data.go from WordBreakProperty.txt
// Run with: go run generate_word_data.go

package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

type wbRange struct {
	start    rune
	end      rune
	property string
}

func main() {
	file, err := os.Open("WordBreakProperty.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error opening file: %v\n", err)
		fmt.Fprintf(os.Stderr, "Please download WordBreakProperty.txt from:\n")
		fmt.Fprintf(os.Stderr, "https://www.unicode.org/Public/17.0.0/ucd/auxiliary/WordBreakProperty.txt\n")
		os.Exit(1)
	}
	defer file.Close()

	var ranges []wbRange
	scanner := bufio.NewScanner(file)
	var version string

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Extract version from first line
		if version == "" && strings.HasPrefix(line, "# WordBreakProperty-") {
			version = strings.TrimPrefix(line, "# WordBreakProperty-")
			version = strings.TrimSuffix(version, ".txt")
		}

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Skip @missing lines
		if strings.HasPrefix(line, "@missing") {
			continue
		}

		// Split on semicolon
		parts := strings.Split(line, ";")
		if len(parts) < 2 {
			continue
		}

		codePoints := strings.TrimSpace(parts[0])
		property := strings.TrimSpace(parts[1])

		// Extract just the property value (before the #)
		if idx := strings.Index(property, "#"); idx != -1 {
			property = strings.TrimSpace(property[:idx])
		}

		// Parse code point or range
		var start, end rune
		if strings.Contains(codePoints, "..") {
			// Range
			rangeParts := strings.Split(codePoints, "..")
			startVal, _ := strconv.ParseInt(rangeParts[0], 16, 32)
			endVal, _ := strconv.ParseInt(rangeParts[1], 16, 32)
			start = rune(startVal)
			end = rune(endVal)
		} else {
			// Single code point
			val, _ := strconv.ParseInt(codePoints, 16, 32)
			start = rune(val)
			end = rune(val)
		}

		ranges = append(ranges, wbRange{start: start, end: end, property: property})
	}

	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "Error reading file: %v\n", err)
		os.Exit(1)
	}

	// Sort ranges by start code point for binary search
	sort.Slice(ranges, func(i, j int) bool {
		return ranges[i].start < ranges[j].start
	})

	// Generate the output file
	out, err := os.Create("word_data.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate_word_data.go DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: Unicode WordBreakProperty-%s.txt\n", version)
	fmt.Fprintf(out, "\npackage uax29\n\n")
	fmt.Fprintf(out, "type wbRange struct {\n")
	fmt.Fprintf(out, "\tstart rune\n")
	fmt.Fprintf(out, "\tend   rune\n")
	fmt.Fprintf(out, "\tclass WordBreakClass\n")
	fmt.Fprintf(out, "}\n\n")
	fmt.Fprintf(out, "// wordBreakData contains all Unicode Word_Break property assignments\n")
	fmt.Fprintf(out, "var wordBreakData = []wbRange{\n")

	for _, r := range ranges {
		var class string
		switch r.property {
		case "CR":
			class = "WBCR"
		case "LF":
			class = "WBLF"
		case "Newline":
			class = "WBNewline"
		case "Extend":
			class = "WBExtend"
		case "ZWJ":
			class = "WBZWJ"
		case "Regional_Indicator":
			class = "WBRegionalIndicator"
		case "Format":
			class = "WBFormat"
		case "Katakana":
			class = "WBKatakana"
		case "Hebrew_Letter":
			class = "WBHebrewLetter"
		case "ALetter":
			class = "WBALetter"
		case "Single_Quote":
			class = "WBSingleQuote"
		case "Double_Quote":
			class = "WBDoubleQuote"
		case "MidNumLet":
			class = "WBMidNumLet"
		case "MidLetter":
			class = "WBMidLetter"
		case "MidNum":
			class = "WBMidNum"
		case "Numeric":
			class = "WBNumeric"
		case "ExtendNumLet":
			class = "WBExtendNumLet"
		case "WSegSpace":
			class = "WBWSegSpace"
		case "Extended_Pictographic":
			class = "WBExtendedPictographic"
		default:
			// Skip Other - it's the default
			continue
		}

		if r.start == r.end {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, %s}, // U+%04X\n", r.start, r.end, class, r.start)
		} else {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, %s}, // U+%04X..U+%04X\n", r.start, r.end, class, r.start, r.end)
		}
	}

	fmt.Fprintf(out, "}\n")
	fmt.Println("Generated word_data.go successfully")
	fmt.Printf("Total ranges: %d\n", len(ranges))
}
