//go:build ignore
// +build ignore

// This program generates confusables_data.go from Unicode confusables.txt
// Run with: go run generate_confusables.go

package main

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

const confusablesURL = "https://www.unicode.org/Public/security/latest/confusables.txt"

type confusableMapping struct {
	source rune
	target string // May be multiple runes
	typ    string // MA, SL, ML, SA
}

func main() {
	// Download confusables.txt
	fmt.Println("Downloading confusables.txt...")
	resp, err := http.Get(confusablesURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error downloading confusables.txt: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Fprintf(os.Stderr, "Error: HTTP %d\n", resp.StatusCode)
		os.Exit(1)
	}

	// Parse the file
	mappings := parseConfusables(resp.Body)
	fmt.Printf("Parsed %d confusable mappings\n", len(mappings))

	// Generate Go code
	generateConfusablesFile(mappings)
	fmt.Println("Generated confusables_data.go")
}

func parseConfusables(r io.Reader) []confusableMapping {
	scanner := bufio.NewScanner(r)
	var mappings []confusableMapping

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip comments and empty lines
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Parse line: SOURCE ; TARGET ; TYPE # COMMENT
		parts := strings.Split(line, ";")
		if len(parts) < 3 {
			continue
		}

		// Parse source code point
		sourceStr := strings.TrimSpace(parts[0])
		sourceVal, err := strconv.ParseInt(sourceStr, 16, 32)
		if err != nil {
			continue
		}

		// Parse target code point(s)
		targetStr := strings.TrimSpace(parts[1])
		targetRunes := parseCodePoints(targetStr)
		if len(targetRunes) == 0 {
			continue
		}

		// Parse type
		typePart := strings.TrimSpace(parts[2])
		typ := strings.Fields(typePart)[0]

		mappings = append(mappings, confusableMapping{
			source: rune(sourceVal),
			target: string(targetRunes),
			typ:    typ,
		})
	}

	// Sort by source for binary search
	sort.Slice(mappings, func(i, j int) bool {
		return mappings[i].source < mappings[j].source
	})

	return mappings
}

func parseCodePoints(s string) []rune {
	parts := strings.Fields(s)
	runes := make([]rune, 0, len(parts))

	for _, part := range parts {
		val, err := strconv.ParseInt(part, 16, 32)
		if err != nil {
			continue
		}
		runes = append(runes, rune(val))
	}

	return runes
}

func generateConfusablesFile(mappings []confusableMapping) {
	f, err := os.Create("confusables_data.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating confusables_data.go: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintf(f, `// Code generated by generate_confusables.go. DO NOT EDIT.
// Source: %s

package uts39

// confusableEntry represents a confusable character mapping
type confusableEntry struct {
	source rune
	target string
}

// confusablesData contains all confusable character mappings
// Used for the skeleton algorithm in confusable detection
var confusablesData = []confusableEntry{
`, confusablesURL)

	for _, m := range mappings {
		// Escape the target string for Go
		targetEscaped := fmt.Sprintf("%+q", m.target)
		fmt.Fprintf(f, "\t{0x%04X, %s}, // %c → %s (%s)\n",
			m.source, targetEscaped, m.source, m.target, m.typ)
	}

	fmt.Fprintf(f, "}\n")
}
