//go:build ignore
// +build ignore

// This program generates bracket_data.go from BidiBrackets.txt
// Run with: go run generate_bracket_data.go

package main

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	bracketDataURL = "https://www.unicode.org/Public/UCD/latest/ucd/BidiBrackets.txt"
	unicodeVersion = "17.0.0"
)

type runeRange struct {
	start rune
	end   rune
}

type bracketEntry struct {
	paired rune
	isOpen bool
}

type bracketMap map[runeRange]bracketEntry

func main() {
	fmt.Println("Downloading Unicode BidiBrackets property file...")

	brackets, err := downloadAndParse(bracketDataURL, "BidiBrackets")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing bracket properties: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Parsed %d bracket entries\n", len(brackets))

	ranges := buildRanges(brackets)
	fmt.Printf("Created %d bracket ranges\n", len(ranges))

	fmt.Println("Generating bracket_data.go...")
	if err := generateCode(ranges); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating code: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully generated bracket_data.go")
}

func downloadAndParse(url, name string) (bracketMap, error) {
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("failed to download %s: %w", name, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("failed to download %s: status %d", name, resp.StatusCode)
	}

	return parsePropertyFile(resp.Body)
}

func parsePropertyFile(r io.Reader) (bracketMap, error) {
	brackets := make(bracketMap)
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.Split(line, ";")
		if len(parts) < 3 {
			continue
		}

		cpStr := strings.TrimSpace(parts[0])
		pairedStr := strings.TrimSpace(parts[1])
		typeStr := strings.Fields(parts[2])[0]

		if typeStr == "n" {
			continue
		}

		var start, end rune
		if strings.Contains(cpStr, "..") {
			rangeParts := strings.Split(cpStr, "..")
			startVal, err := strconv.ParseInt(rangeParts[0], 16, 32)
			if err != nil {
				continue
			}
			endVal, err := strconv.ParseInt(rangeParts[1], 16, 32)
			if err != nil {
				continue
			}
			start = rune(startVal)
			end = rune(endVal)
		} else {
			val, err := strconv.ParseInt(cpStr, 16, 32)
			if err != nil {
				continue
			}
			start = rune(val)
			end = rune(val)
		}

		paired, err := strconv.ParseInt(pairedStr, 16, 32)
		if err != nil {
			continue
		}

		brackets[runeRange{start, end}] = bracketEntry{
			paired: rune(paired),
			isOpen: typeStr == "o",
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return brackets, nil
}

// bracketRange holds bracket pairing information for a codepoint range.
type bracketRange struct {
	start  rune
	end    rune
	paired rune
	isOpen bool
}

func buildRanges(brackets bracketMap) []bracketRange {
	boundarySet := make(map[rune]bool)
	for rng := range brackets {
		boundarySet[rng.start] = true
		if rng.end < 0x10FFFF {
			boundarySet[rng.end+1] = true
		}
	}

	boundaries := make([]rune, 0, len(boundarySet))
	for b := range boundarySet {
		boundaries = append(boundaries, b)
	}
	sort.Slice(boundaries, func(i, j int) bool {
		return boundaries[i] < boundaries[j]
	})

	var ranges []bracketRange
	for i := 0; i < len(boundaries)-1; i++ {
		start := boundaries[i]
		end := boundaries[i+1] - 1

		entry, ok := lookupProperty(brackets, start)
		if ok {
			ranges = append(ranges, bracketRange{
				start:  start,
				end:    end,
				paired: entry.paired,
				isOpen: entry.isOpen,
			})
		}
	}

	return ranges
}

func lookupProperty(bm bracketMap, r rune) (bracketEntry, bool) {
	for rng, entry := range bm {
		if r >= rng.start && r <= rng.end {
			return entry, true
		}
	}
	return bracketEntry{}, false
}

func generateCode(ranges []bracketRange) error {
	out, err := os.Create("bracket_data.go")
	if err != nil {
		return err
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate_bracket_data.go. DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: Unicode BidiBrackets-%s.txt\n", unicodeVersion)
	fmt.Fprint(out, "\npackage uax9\n\n")

	fmt.Fprint(out, "// bracketRange holds bracket pairing information for a codepoint range.\n")
	fmt.Fprint(out, "type bracketRange struct {\n")
	fmt.Fprint(out, "\tstart  rune\n")
	fmt.Fprint(out, "\tend    rune\n")
	fmt.Fprint(out, "\tpaired rune\n")
	fmt.Fprint(out, "\tisOpen bool\n")
	fmt.Fprint(out, "}\n\n")

	fmt.Fprintf(out, "// bracketData contains all Unicode BidiBrackets.txt property assignments.\n")
	fmt.Fprintf(out, "// Total ranges: %d\n", len(ranges))
	fmt.Fprint(out, "var bracketData = []bracketRange{\n")

	for _, r := range ranges {
		typ := "c"
		if r.isOpen {
			typ = "o"
		}
		if r.start == r.end {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, 0x%04X, %v}, // U+%04X %s\n",
				r.start, r.end, r.paired, r.isOpen, r.start, typ)
		} else {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, 0x%04X, %v}, // U+%04X..U+%04X %s\n",
				r.start, r.end, r.paired, r.isOpen, r.start, r.end, typ)
		}
	}

	fmt.Fprint(out, "}\n\n")

	fmt.Fprint(out, "// getBracketData returns the paired bracket and open/close status for a rune.\n")
	fmt.Fprint(out, "// Returns ok=false if the rune is not a bracketed character.\n")
	fmt.Fprint(out, "func getBracketData(r rune) (paired rune, isOpen bool, ok bool) {\n")
	fmt.Fprint(out, "\tleft, right := 0, len(bracketData)-1\n")
	fmt.Fprint(out, "\tfor left <= right {\n")
	fmt.Fprint(out, "\t\tmid := (left + right) / 2\n")
	fmt.Fprint(out, "\t\tentry := bracketData[mid]\n")
	fmt.Fprint(out, "\t\tif r < entry.start {\n")
	fmt.Fprint(out, "\t\t\tright = mid - 1\n")
	fmt.Fprint(out, "\t\t} else if r > entry.end {\n")
	fmt.Fprint(out, "\t\t\tleft = mid + 1\n")
	fmt.Fprint(out, "\t\t} else {\n")
	fmt.Fprint(out, "\t\t\treturn entry.paired, entry.isOpen, true\n")
	fmt.Fprint(out, "\t\t}\n")
	fmt.Fprint(out, "\t}\n")
	fmt.Fprint(out, "\treturn 0, false, false\n")
	fmt.Fprint(out, "}\n")

	return nil
}
