// +build ignore

// This program generates bidi_data.go from DerivedBidiClass.txt
// Run with: go run generate_bidi_data.go

package main

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	bidiClassURL   = "https://www.unicode.org/Public/17.0.0/ucd/extracted/DerivedBidiClass.txt"
	unicodeVersion = "17.0.0"
)

type runeRange struct {
	start rune
	end   rune
}

type propertyMap map[runeRange]string

func main() {
	fmt.Println("Downloading Unicode BidiClass property file...")

	// Download and parse property file
	bidiProps, err := downloadAndParse(bidiClassURL, "DerivedBidiClass")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing bidi properties: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Parsed %d bidi class ranges\n", len(bidiProps))

	// Convert to sorted slice
	ranges := buildRanges(bidiProps)
	fmt.Printf("Created %d bidi class ranges\n", len(ranges))

	// Generate output file
	fmt.Println("Generating bidi_data.go...")
	if err := generateCode(ranges); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating code: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully generated bidi_data.go")
}

func downloadAndParse(url, name string) (propertyMap, error) {
	// Try to download
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("failed to download %s: %w", name, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("failed to download %s: status %d", name, resp.StatusCode)
	}

	return parsePropertyFile(resp.Body)
}

func parsePropertyFile(r io.Reader) (propertyMap, error) {
	props := make(propertyMap)
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Split on semicolon: code_point(s) ; property # comment
		parts := strings.Split(line, ";")
		if len(parts) < 2 {
			continue
		}

		codePoints := strings.TrimSpace(parts[0])
		property := strings.TrimSpace(parts[1])

		// Extract just the property name (before any comment)
		property = strings.Fields(property)[0]

		// Parse code point or range
		var start, end rune
		if strings.Contains(codePoints, "..") {
			// Range: 0000..001F
			rangeParts := strings.Split(codePoints, "..")
			startVal, err := strconv.ParseInt(rangeParts[0], 16, 32)
			if err != nil {
				continue
			}
			endVal, err := strconv.ParseInt(rangeParts[1], 16, 32)
			if err != nil {
				continue
			}
			start = rune(startVal)
			end = rune(endVal)
		} else {
			// Single code point: 0020
			val, err := strconv.ParseInt(codePoints, 16, 32)
			if err != nil {
				continue
			}
			start = rune(val)
			end = rune(val)
		}

		props[runeRange{start, end}] = property
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return props, nil
}

type bidiRange struct {
	start rune
	end   rune
	class string
}

func buildRanges(props propertyMap) []bidiRange {
	// Collect all boundary points
	boundarySet := make(map[rune]bool)

	for rng := range props {
		boundarySet[rng.start] = true
		if rng.end < 0x10FFFF {
			boundarySet[rng.end+1] = true
		}
	}

	// Convert to sorted slice
	boundaries := make([]rune, 0, len(boundarySet))
	for b := range boundarySet {
		boundaries = append(boundaries, b)
	}
	sort.Slice(boundaries, func(i, j int) bool {
		return boundaries[i] < boundaries[j]
	})

	// Build ranges
	var ranges []bidiRange
	for i := 0; i < len(boundaries)-1; i++ {
		start := boundaries[i]
		end := boundaries[i+1] - 1

		// Look up property for this range
		prop := lookupProperty(props, start, "L") // Default to L (Left-to-Right)

		ranges = append(ranges, bidiRange{
			start: start,
			end:   end,
			class: prop,
		})
	}

	return ranges
}

func lookupProperty(pm propertyMap, r rune, defaultProp string) string {
	for rng, prop := range pm {
		if r >= rng.start && r <= rng.end {
			return prop
		}
	}
	return defaultProp
}

func generateCode(ranges []bidiRange) error {
	out, err := os.Create("bidi_data.go")
	if err != nil {
		return err
	}
	defer out.Close()

	// File header
	fmt.Fprintf(out, "// Code generated by generate_bidi_data.go. DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: Unicode DerivedBidiClass-%s.txt\n", unicodeVersion)
	fmt.Fprintf(out, "\npackage uax9\n\n")

	// Type definition
	fmt.Fprintf(out, "type bidiRange struct {\n")
	fmt.Fprintf(out, "\tstart rune\n")
	fmt.Fprintf(out, "\tend   rune\n")
	fmt.Fprintf(out, "\tclass BidiClass\n")
	fmt.Fprintf(out, "}\n\n")

	// Data table
	fmt.Fprintf(out, "// bidiData contains all Unicode BidiClass property assignments\n")
	fmt.Fprintf(out, "// Total ranges: %d\n", len(ranges))
	fmt.Fprintf(out, "var bidiData = []bidiRange{\n")

	for _, r := range ranges {
		className := mapBidiClassName(r.class)
		comment := ""
		if r.start == r.end {
			comment = fmt.Sprintf("// U+%04X %s", r.start, r.class)
		} else {
			comment = fmt.Sprintf("// U+%04X..U+%04X %s", r.start, r.end, r.class)
		}

		fmt.Fprintf(out, "\t{0x%04X, 0x%04X, Class%s}, %s\n", r.start, r.end, className, comment)
	}

	fmt.Fprintf(out, "}\n\n")

	// Classification function
	fmt.Fprintf(out, "// getBidiClassFromData returns the BidiClass for a rune using binary search\n")
	fmt.Fprintf(out, "func getBidiClassFromData(r rune) BidiClass {\n")
	fmt.Fprintf(out, "\tleft, right := 0, len(bidiData)-1\n")
	fmt.Fprintf(out, "\tfor left <= right {\n")
	fmt.Fprintf(out, "\t\tmid := (left + right) / 2\n")
	fmt.Fprintf(out, "\t\tentry := bidiData[mid]\n")
	fmt.Fprintf(out, "\t\tif r < entry.start {\n")
	fmt.Fprintf(out, "\t\t\tright = mid - 1\n")
	fmt.Fprintf(out, "\t\t} else if r > entry.end {\n")
	fmt.Fprintf(out, "\t\t\tleft = mid + 1\n")
	fmt.Fprintf(out, "\t\t} else {\n")
	fmt.Fprintf(out, "\t\t\treturn entry.class\n")
	fmt.Fprintf(out, "\t\t}\n")
	fmt.Fprintf(out, "\t}\n")
	fmt.Fprintf(out, "\treturn ClassL // Default to Left-to-Right\n")
	fmt.Fprintf(out, "}\n")

	return nil
}

// Map Unicode property names to Go constant names
func mapBidiClassName(prop string) string {
	switch prop {
	case "L":
		return "L"
	case "R":
		return "R"
	case "AL":
		return "AL"
	case "EN":
		return "EN"
	case "ES":
		return "ES"
	case "ET":
		return "ET"
	case "AN":
		return "AN"
	case "CS":
		return "CS"
	case "NSM":
		return "NSM"
	case "BN":
		return "BN"
	case "B":
		return "B"
	case "S":
		return "S"
	case "WS":
		return "WS"
	case "ON":
		return "ON"
	case "LRE":
		return "LRE"
	case "LRO":
		return "LRO"
	case "RLE":
		return "RLE"
	case "RLO":
		return "RLO"
	case "PDF":
		return "PDF"
	case "LRI":
		return "LRI"
	case "RLI":
		return "RLI"
	case "FSI":
		return "FSI"
	case "PDI":
		return "PDI"
	default:
		return "L" // Default to Left-to-Right
	}
}
