// +build ignore

// This program generates identifier_data.go from Unicode data files
// Run with: go run generate_identifier_data.go

package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

type idRange struct {
	start rune
	end   rune
}

func main() {
	// Parse DerivedCoreProperties.txt for XID_Start and XID_Continue
	xidStart := parseProperty("DerivedCoreProperties.txt", "XID_Start")
	xidContinue := parseProperty("DerivedCoreProperties.txt", "XID_Continue")

	// Parse PropList.txt for Pattern_Syntax and Pattern_White_Space
	patternSyntax := parseProperty("PropList.txt", "Pattern_Syntax")
	patternWhiteSpace := parseProperty("PropList.txt", "Pattern_White_Space")

	// Generate the output file
	out, err := os.Create("identifier_data.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate_identifier_data.go DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: Unicode 17.0.0\n")
	fmt.Fprintf(out, "\npackage uax31\n\n")
	fmt.Fprintf(out, "type idRange struct {\n")
	fmt.Fprintf(out, "\tstart rune\n")
	fmt.Fprintf(out, "\tend   rune\n")
	fmt.Fprintf(out, "}\n\n")

	// XID_Start
	fmt.Fprintf(out, "// xidStartData contains all Unicode XID_Start property assignments\n")
	fmt.Fprintf(out, "// Total ranges: %d\n", len(xidStart))
	fmt.Fprintf(out, "var xidStartData = []idRange{\n")
	writeRanges(out, xidStart)
	fmt.Fprintf(out, "}\n\n")

	// XID_Continue
	fmt.Fprintf(out, "// xidContinueData contains all Unicode XID_Continue property assignments\n")
	fmt.Fprintf(out, "// Total ranges: %d\n", len(xidContinue))
	fmt.Fprintf(out, "var xidContinueData = []idRange{\n")
	writeRanges(out, xidContinue)
	fmt.Fprintf(out, "}\n\n")

	// Pattern_Syntax
	fmt.Fprintf(out, "// patternSyntaxData contains all Unicode Pattern_Syntax property assignments\n")
	fmt.Fprintf(out, "// Total ranges: %d\n", len(patternSyntax))
	fmt.Fprintf(out, "var patternSyntaxData = []idRange{\n")
	writeRanges(out, patternSyntax)
	fmt.Fprintf(out, "}\n\n")

	// Pattern_White_Space
	fmt.Fprintf(out, "// patternWhiteSpaceData contains all Unicode Pattern_White_Space property assignments\n")
	fmt.Fprintf(out, "// Total ranges: %d\n", len(patternWhiteSpace))
	fmt.Fprintf(out, "var patternWhiteSpaceData = []idRange{\n")
	writeRanges(out, patternWhiteSpace)
	fmt.Fprintf(out, "}\n")

	fmt.Printf("Generated identifier_data.go successfully\n")
	fmt.Printf("  XID_Start: %d ranges\n", len(xidStart))
	fmt.Printf("  XID_Continue: %d ranges\n", len(xidContinue))
	fmt.Printf("  Pattern_Syntax: %d ranges\n", len(patternSyntax))
	fmt.Printf("  Pattern_White_Space: %d ranges\n", len(patternWhiteSpace))
}

func parseProperty(filename, property string) []idRange {
	file, err := os.Open(filename)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error opening %s: %v\n", filename, err)
		os.Exit(1)
	}
	defer file.Close()

	var ranges []idRange
	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Split on semicolon
		parts := strings.Split(line, ";")
		if len(parts) < 2 {
			continue
		}

		codePoints := strings.TrimSpace(parts[0])
		propName := strings.TrimSpace(parts[1])

		// Extract just the property name (before any # comment)
		propName = strings.Fields(propName)[0]

		// Check if this is the property we're looking for
		if propName != property {
			continue
		}

		// Parse code point or range
		var start, end rune
		if strings.Contains(codePoints, "..") {
			// Range
			rangeParts := strings.Split(codePoints, "..")
			startVal, _ := strconv.ParseInt(rangeParts[0], 16, 32)
			endVal, _ := strconv.ParseInt(rangeParts[1], 16, 32)
			start = rune(startVal)
			end = rune(endVal)
		} else {
			// Single code point
			val, _ := strconv.ParseInt(codePoints, 16, 32)
			start = rune(val)
			end = rune(val)
		}

		ranges = append(ranges, idRange{start: start, end: end})
	}

	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", filename, err)
		os.Exit(1)
	}

	return ranges
}

func writeRanges(out *os.File, ranges []idRange) {
	for _, r := range ranges {
		if r.start == r.end {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X}, // U+%04X\n", r.start, r.end, r.start)
		} else {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X}, // U+%04X..U+%04X\n", r.start, r.end, r.start, r.end)
		}
	}
}
