// +build ignore

// This program generates east_asian_width_data.go from EastAsianWidth.txt
// Run with: go run generate_eaw_data.go

package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

type eawRange struct {
	start rune
	end   rune
	value string // A, F, H, N, Na, or W
}

func main() {
	file, err := os.Open("EastAsianWidth.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error opening file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	var ranges []eawRange
	scanner := bufio.NewScanner(file)
	var version string

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Extract version from first line
		if version == "" && strings.HasPrefix(line, "# EastAsianWidth-") {
			version = strings.TrimPrefix(line, "# EastAsianWidth-")
			version = strings.TrimSuffix(version, ".txt")
		}

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Split on semicolon
		parts := strings.Split(line, ";")
		if len(parts) < 2 {
			continue
		}

		codePoints := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		// Extract just the property value (A, F, H, N, Na, W)
		value = strings.Fields(value)[0]

		// Parse code point or range
		var start, end rune
		if strings.Contains(codePoints, "..") {
			// Range
			rangeParts := strings.Split(codePoints, "..")
			startVal, _ := strconv.ParseInt(rangeParts[0], 16, 32)
			endVal, _ := strconv.ParseInt(rangeParts[1], 16, 32)
			start = rune(startVal)
			end = rune(endVal)
		} else {
			// Single code point
			val, _ := strconv.ParseInt(codePoints, 16, 32)
			start = rune(val)
			end = rune(val)
		}

		ranges = append(ranges, eawRange{start: start, end: end, value: value})
	}

	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "Error reading file: %v\n", err)
		os.Exit(1)
	}

	// Generate the output file
	out, err := os.Create("east_asian_width_data.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate_eaw_data.go DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: Unicode EastAsianWidth-%s.txt\n", version)
	fmt.Fprintf(out, "\npackage uax11\n\n")
	fmt.Fprintf(out, "type eawRange struct {\n")
	fmt.Fprintf(out, "\tstart rune\n")
	fmt.Fprintf(out, "\tend   rune\n")
	fmt.Fprintf(out, "\twidth Width\n")
	fmt.Fprintf(out, "}\n\n")
	fmt.Fprintf(out, "// eastAsianWidthData contains all Unicode East Asian Width property assignments\n")
	fmt.Fprintf(out, "var eastAsianWidthData = []eawRange{\n")

	for _, r := range ranges {
		var width string
		switch r.value {
		case "A":
			width = "Ambiguous"
		case "F":
			width = "Fullwidth"
		case "H":
			width = "Halfwidth"
		case "N":
			width = "Neutral"
		case "Na":
			width = "Narrow"
		case "W":
			width = "Wide"
		}

		if r.start == r.end {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, %s}, // U+%04X\n", r.start, r.end, width, r.start)
		} else {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, %s}, // U+%04X..U+%04X\n", r.start, r.end, width, r.start, r.end)
		}
	}

	fmt.Fprintf(out, "}\n")
	fmt.Println("Generated east_asian_width_data.go successfully")
}
