//go:build ignore
// +build ignore

// This program generates vertical_orientation_data.go from VerticalOrientation.txt
// Run with: go run generate_vo_data.go

package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

type voRange struct {
	start rune
	end   rune
	value string // R, U, Tu, or Tr
}

func main() {
	file, err := os.Open("VerticalOrientation.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error opening file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	var ranges []voRange
	scanner := bufio.NewScanner(file)
	var version string

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Extract version from first line
		if version == "" && strings.HasPrefix(line, "# VerticalOrientation-") {
			version = strings.TrimPrefix(line, "# VerticalOrientation-")
			version = strings.TrimSuffix(version, ".txt")
		}

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Split on semicolon
		parts := strings.Split(line, ";")
		if len(parts) < 2 {
			continue
		}

		codePoints := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		// Extract just the property value (R, U, Tu, Tr)
		value = strings.Fields(value)[0]

		// Parse code point or range
		var start, end rune
		if strings.Contains(codePoints, "..") {
			// Range
			rangeParts := strings.Split(codePoints, "..")
			startVal, _ := strconv.ParseInt(rangeParts[0], 16, 32)
			endVal, _ := strconv.ParseInt(rangeParts[1], 16, 32)
			start = rune(startVal)
			end = rune(endVal)
		} else {
			// Single code point
			val, _ := strconv.ParseInt(codePoints, 16, 32)
			start = rune(val)
			end = rune(val)
		}

		ranges = append(ranges, voRange{start: start, end: end, value: value})
	}

	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "Error reading file: %v\n", err)
		os.Exit(1)
	}

	// Generate the output file
	out, err := os.Create("vertical_orientation_data.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate_vo_data.go DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: Unicode VerticalOrientation-%s.txt\n", version)
	fmt.Fprintf(out, "\npackage uax50\n\n")
	fmt.Fprintf(out, "type voRange struct {\n")
	fmt.Fprintf(out, "\tstart rune\n")
	fmt.Fprintf(out, "\tend   rune\n")
	fmt.Fprintf(out, "\tvalue Orientation\n")
	fmt.Fprintf(out, "}\n\n")
	fmt.Fprintf(out, "// verticalOrientationData contains all Unicode vertical orientation property assignments\n")
	fmt.Fprintf(out, "var verticalOrientationData = []voRange{\n")

	for _, r := range ranges {
		var orientation string
		switch r.value {
		case "R":
			orientation = "Rotated"
		case "U":
			orientation = "Upright"
		case "Tu":
			orientation = "TransformedUpright"
		case "Tr":
			orientation = "TransformedRotated"
		}

		if r.start == r.end {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, %s}, // U+%04X\n", r.start, r.end, orientation, r.start)
		} else {
			fmt.Fprintf(out, "\t{0x%04X, 0x%04X, %s}, // U+%04X..U+%04X\n", r.start, r.end, orientation, r.start, r.end)
		}
	}

	fmt.Fprintf(out, "}\n")
	fmt.Println("Generated vertical_orientation_data.go successfully")
}
