//go:build ignore
// +build ignore

// This program generates emoji_data.go from emoji-data.txt
// Run with: go run generate_emoji_data.go

package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

type property struct {
	name   string
	ranges []rangeEntry
}

type rangeEntry struct {
	start rune
	end   rune
}

func main() {
	file, err := os.Open("emoji-data.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error opening file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	// Map to collect ranges for each property
	properties := make(map[string][]rangeEntry)
	scanner := bufio.NewScanner(file)
	var version string

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Extract version
		if version == "" && strings.HasPrefix(line, "# Version:") {
			version = strings.TrimSpace(strings.TrimPrefix(line, "# Version:"))
		}

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Split on semicolon
		parts := strings.Split(line, ";")
		if len(parts) < 2 {
			continue
		}

		codePoints := strings.TrimSpace(parts[0])
		propertyPart := strings.TrimSpace(parts[1])

		// Extract property name (before any comments)
		propName := strings.Fields(propertyPart)[0]
		// Remove any trailing # or other invalid characters
		propName = strings.TrimRight(propName, "#")

		// Parse code point or range
		var start, end rune
		if strings.Contains(codePoints, "..") {
			// Range
			rangeParts := strings.Split(codePoints, "..")
			startVal, _ := strconv.ParseInt(rangeParts[0], 16, 32)
			endVal, _ := strconv.ParseInt(rangeParts[1], 16, 32)
			start = rune(startVal)
			end = rune(endVal)
		} else {
			// Single code point
			val, _ := strconv.ParseInt(codePoints, 16, 32)
			start = rune(val)
			end = rune(val)
		}

		properties[propName] = append(properties[propName], rangeEntry{start: start, end: end})
	}

	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "Error reading file: %v\n", err)
		os.Exit(1)
	}

	// Generate the output file
	out, err := os.Create("emoji_data.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate_emoji_data.go DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: Unicode emoji-data.txt Version %s\n", version)
	fmt.Fprintf(out, "\npackage uts51\n\n")

	// Generate property check functions
	fmt.Fprintf(out, "type emojiRange struct {\n")
	fmt.Fprintf(out, "\tstart rune\n")
	fmt.Fprintf(out, "\tend   rune\n")
	fmt.Fprintf(out, "}\n\n")

	// Generate data for each property
	for propName, ranges := range properties {
		varName := propertyToVarName(propName)
		fmt.Fprintf(out, "// %sRanges contains code points with the %s property\n", varName, propName)
		fmt.Fprintf(out, "// See UTS #51: https://www.unicode.org/reports/tr51/\n")
		fmt.Fprintf(out, "var %sRanges = []emojiRange{\n", varName)

		for _, r := range ranges {
			if r.start == r.end {
				fmt.Fprintf(out, "\t{0x%04X, 0x%04X}, // U+%04X\n", r.start, r.end, r.start)
			} else {
				fmt.Fprintf(out, "\t{0x%04X, 0x%04X}, // U+%04X..U+%04X\n", r.start, r.end, r.start, r.end)
			}
		}

		fmt.Fprintf(out, "}\n\n")
	}

	fmt.Println("Generated emoji_data.go successfully")
}

func propertyToVarName(prop string) string {
	// Convert property names to Go variable names
	// Emoji -> emoji
	// Emoji_Presentation -> emojiPresentation
	// Emoji_Modifier -> emojiModifier
	// etc.
	parts := strings.Split(prop, "_")
	result := strings.ToLower(parts[0])
	for i := 1; i < len(parts); i++ {
		part := strings.ToLower(parts[i])
		if len(part) > 0 {
			result += strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return result
}
